[package]
name = "voxelworld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bgfx-rs = "0.19"
winit = "0.29"
raw-window-handle = "0.6"
glam = "0.15"
